services:

  react-mini:
    build:
      context: ../
      dockerfile: .devcontainer/docker/nodejs/Dockerfile
    image: node22-dev
    container_name: ${PROJECT_NAME:?}
    environment:
      - ENV=/${USER_HOME_DIR:-/root}/.ashrc
      - NPM_CONFIG_USER=${USER_NAME:-root}
      - TZ=${TIMEZONE:-Europe/Moscow}
    volumes:
      - ../:/workspace
      - ./.vscode:/${USER_NAME:-root}/.vscode-server
      - ./settings/aliases:/${USER_NAME:-root}/.ashrc
    working_dir: /workspace/app
    ports:
      - "8081:8081"
    restart: unless-stopped
    command: "sleep infinity"
